const app = document.querySelector('#app');
const toastRegion = document.querySelector('#toast-region');
const storage = {
  get(key, fallback) { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } },
  set(key, value) { localStorage.setItem(key, JSON.stringify(value)); }
};
const seed = {
  locations: [
    { id: 1, name: 'Downtown Parking Hub', address: '42 Market Street', distance: '0.3 mi', available: 28, total: 80, price: 4.5, rating: 4.8, status: 'Open', features: ['Security', 'CCTV', 'EV charging'], tone: '' },
    { id: 2, name: 'City Center Smart Parking', address: '18 Grand Avenue', distance: '0.6 mi', available: 12, total: 55, price: 3.75, rating: 4.6, status: 'Open', features: ['Security', 'CCTV'], tone: 'sunset' },
    { id: 3, name: 'Metro Station Parking', address: '7 Transit Way', distance: '0.9 mi', available: 41, total: 120, price: 2.9, rating: 4.5, status: 'Open', features: ['CCTV', 'EV charging'], tone: 'light' },
    { id: 4, name: 'Business District Parking', address: '90 Union Boulevard', distance: '1.2 mi', available: 7, total: 60, price: 5.25, rating: 4.9, status: 'Open', features: ['Security', 'CCTV', 'EV charging'], tone: '' },
    { id: 5, name: 'Mall Parking Zone', address: '150 Riverside Drive', distance: '1.6 mi', available: 63, total: 200, price: 2.5, rating: 4.4, status: 'Open', features: ['CCTV'], tone: 'sunset' }
  ],
  bookings: [
    { id: 'PK-240801', parking: 'Downtown Parking Hub', slot: 'B12', vehicle: 'TN 09 AB 1234', date: '2026-09-07', entry: '09:30', exit: '12:30', amount: 15.2, status: 'Upcoming' },
    { id: 'PK-240734', parking: 'Metro Station Parking', slot: 'C04', vehicle: 'TN 09 AB 1234', date: '2026-08-29', entry: '14:00', exit: '16:00', amount: 6.7, status: 'Completed' },
    { id: 'PK-240699', parking: 'Mall Parking Zone', slot: 'A18', vehicle: 'TN 09 AB 1234', date: '2026-08-19', entry: '11:00', exit: '13:00', amount: 5.7, status: 'Completed' }
  ],
  slots: {}
};
function initialize() {
  if (!storage.get('pm_locations', null)) storage.set('pm_locations', seed.locations);
  if (!storage.get('pm_bookings', null)) storage.set('pm_bookings', seed.bookings);
  if (!storage.get('pm_slots', null)) storage.set('pm_slots', {});
}
initialize();
const state = { selectedLocation: null, selectedSlot: null, booking: {}, paymentMethod: 'card' };
const currentUser = () => storage.get('pm_user', null);
const route = () => location.hash.replace('#/', '') || (currentUser() ? 'dashboard' : 'login');
const money = value => `$${Number(value || 0).toFixed(2)}`;
const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char]));
const initials = name => (name || 'Demo User').split(' ').map(part => part[0]).join('').slice(0, 2).toUpperCase();
function displayNameFromEmail(email) {
  const localPart = email.split('@')[0].replace(/([a-z])([A-Z])/g, '$1 $2').replace(/[._-]+/g, ' ').replace(/\d+/g, ' ').replace(/[^a-zA-Z ]/g, ' ').trim().toLowerCase();
  const words = localPart.split(/\s+/).filter(Boolean);
  if (words.length > 1) return words.slice(0, 2).map(word => word[0].toUpperCase() + word.slice(1)).join(' ');
  const commonFirstNames = ['aman', 'alex', 'anna', 'arjun', 'deepak', 'john', 'rahul', 'ritu', 'rohit', 'sahil', 'sam', 'vijay'];
  const firstName = commonFirstNames.find(name => words[0]?.startsWith(name) && words[0].length > name.length + 1);
  if (firstName) {
    const lastName = words[0].slice(firstName.length);
    return `${firstName[0].toUpperCase() + firstName.slice(1)} ${lastName[0].toUpperCase() + lastName.slice(1)}`;
  }
  return words[0] ? words[0][0].toUpperCase() + words[0].slice(1) : 'Demo User';
}
function toast(message, error = false) { const node = document.createElement('div'); node.className = `toast${error ? ' error' : ''}`; node.textContent = message; toastRegion.append(node); setTimeout(() => node.remove(), 3200); }
function statusClass(status) { return status === 'Completed' || status === 'Confirmed' ? 'success' : status === 'Upcoming' || status === 'Pending' ? 'warning' : status === 'Cancelled' ? 'danger' : 'neutral'; }
function layout(content, active = 'dashboard') {
  const user = currentUser() || { name: 'Demo User', role: 'user' };
  const admin = user.role === 'admin';
  const items = admin ? [['admin', '▦', 'Overview'], ['admin-locations', '⌂', 'Parking Locations'], ['admin-slots', '◈', 'Parking Slots'], ['admin-bookings', '▤', 'Bookings'], ['reports', '◌', 'Reports'], ['settings', '⚙', 'Settings']] : [['dashboard', '⌂', 'Dashboard'], ['parking', '⌖', 'Find Parking'], ['bookings', '▤', 'My Bookings'], ['settings', '⚙', 'Settings']];
  return `<div class="app-shell"><aside class="sidebar" id="sidebar"><div class="brand"><span class="brand-mark"></span> parkly</div><div class="nav-label">Workspace</div><nav class="nav-list">${items.map(([href, icon, label]) => `<button class="nav-item ${active === href ? 'active' : ''}" data-route="${href}"><span class="nav-icon">${icon}</span>${label}</button>`).join('')}</nav><div class="sidebar-footer"><div class="user-mini"><span class="avatar">${initials(user.name)}</span><div><strong>${escapeHtml(user.name)}</strong><small>${admin ? 'Administrator' : 'Personal account'}</small></div></div><button class="nav-item" id="logout"><span class="nav-icon">↪</span>Sign out</button></div></aside><main class="content"><header class="topbar"><div class="topbar-left"><button class="mobile-menu" id="mobile-menu">☰</button><div class="breadcrumb">Workspace <span>/</span> <strong>${escapeHtml(pageTitle(active))}</strong></div></div><div class="top-actions"><button class="icon-button" id="notify" aria-label="Notifications">♧</button><span class="avatar">${initials(user.name)}</span><span class="profile-label"><strong>${escapeHtml(user.name)}</strong></span></div></header>${content}<footer class="site-footer"><div class="footer-copy"><strong>© 2026 Parkly. All rights reserved.</strong><span><strong>Parking Management System</strong> — Smart, simple and secure parking management.</span></div><strong class="footer-credit">Made by Ritu Raj</strong></footer></main></div>`;
}
function pageTitle(active) { return ({ dashboard: 'Dashboard', parking: 'Find parking', slots: 'Select a slot', booking: 'Booking details', payment: 'Payment', confirmation: 'Confirmation', bookings: 'My bookings', admin: 'Admin overview', 'admin-locations': 'Parking locations', 'admin-slots': 'Parking slots', 'admin-bookings': 'All bookings', reports: 'Reports', settings: 'Settings' })[active] || 'Dashboard'; }
function stat(label, value, icon, tone = '') { return `<div class="stat-card"><div class="stat-icon ${tone}">${icon}</div><div><div class="stat-label">${label}</div><div class="stat-value">${value}</div><div class="stat-change">↗ 12.5% this month</div></div></div>`; }
function dashboard() { const bookings = storage.get('pm_bookings', seed.bookings); const active = bookings.find(b => b.status === 'Upcoming') || bookings[0]; return layout(`<section class="page"><div class="page-heading"><div><h1>Good evening, ${escapeHtml((currentUser()?.name || 'Alex').split(' ')[0])}.</h1><p class="subtitle">Here is what's happening with your parking today.</p></div><button class="btn btn-primary" data-route="parking">+ Find parking</button></div><div class="stats-grid">${stat('Active booking', active ? '1' : '0', '⌖', '')}${stat('Available spots', '148', '◈', 'blue')}${stat('Total bookings', bookings.length, '▤', 'peach')}${stat('Amount spent', money(bookings.reduce((sum, booking) => sum + booking.amount, 0)), '$', 'purple')}</div><div class="grid-2"><div class="card booking-card"><div class="card-header"><div><div class="stat-label">CURRENT BOOKING</div><h2>${active ? escapeHtml(active.parking) : 'No active booking'}</h2></div><span class="status success">${active ? active.status : 'Available'}</span></div>${active ? `<p style="color:#9bb5c4">${active.date} · ${active.entry} - ${active.exit}</p><div class="booking-meta"><div><span>Slot</span><strong>${active.slot}</strong></div><div><span>Vehicle</span><strong>${active.vehicle}</strong></div><div><span>Booking ID</span><strong>${active.id}</strong></div></div><div class="code-box" aria-label="Booking code"></div><button class="btn btn-primary" data-route="confirmation">View booking</button>` : '<p style="color:#9bb5c4">Reserve a nearby spot in under a minute.</p>'}</div><div class="card"><div class="card-header"><h2>Activity</h2><button class="link" data-route="bookings">View all</button></div><div class="activity"><div class="activity-row"><span class="activity-dot"></span><p><strong>Payment received</strong><br><small>Today, 9:42 AM · Downtown Parking Hub</small></p></div><div class="activity-row"><span class="activity-dot"></span><p><strong>Booking confirmed</strong><br><small>Yesterday, 4:18 PM · Metro Station</small></p></div><div class="activity-row"><span class="activity-dot"></span><p><strong>Profile updated</strong><br><small>Aug 28, 11:05 AM</small></p></div></div></div></div><div class="card" style="margin-top:20px"><div class="card-header"><h2>Recent bookings</h2><button class="link" data-route="bookings">View all bookings</button></div>${bookingTable(bookings.slice(0, 4))}</div></section>`, 'dashboard'); }
function bookingTable(bookings) { return `<div class="table-wrap"><table><thead><tr><th>Booking ID</th><th>Parking</th><th>Slot</th><th>Date</th><th>Amount</th><th>Status</th></tr></thead><tbody>${bookings.map(b => `<tr><td><strong>${b.id}</strong></td><td>${escapeHtml(b.parking)}</td><td>${b.slot}</td><td>${b.date}</td><td>${money(b.amount)}</td><td><span class="status ${statusClass(b.status)}">${b.status}</span></td></tr>`).join('') || '<tr><td colspan="6">No bookings yet.</td></tr>'}</tbody></table></div>`; }
function parking() { const locations = storage.get('pm_locations', seed.locations); return layout(`<section class="page"><div class="page-heading"><div><h1>Find a parking spot</h1><p class="subtitle">Reserve a space before you arrive. No circling, no stress.</p></div></div><div class="card search-panel"><div class="field"><label>Search location</label><input id="location-search" placeholder="City, street or parking name"></div><div class="field"><label>Date</label><input type="date" id="search-date" value="2026-09-07"></div><div class="field"><label>Entry time</label><input type="time" value="09:30"></div><div class="field"><label>Exit time</label><input type="time" value="12:30"></div><div class="field"><label>Vehicle</label><select><option>Car</option><option>Motorcycle</option><option>EV</option></select></div><button class="btn btn-dark" id="search-parking">Search</button></div><div class="parking-grid" id="parking-results">${locationCards(locations)}</div></section>`, 'parking'); }
function locationCards(locations) { return locations.map(location => `<article class="card parking-card"><div class="parking-cover ${location.tone}"><small>${location.distance} away · <strong>${location.status}</strong></small><h3>${escapeHtml(location.name)}</h3></div><div class="parking-body"><p class="subtitle">${escapeHtml(location.address)} · <strong>★ ${location.rating}</strong></p><div class="parking-details"><span class="tag">${location.available} spots</span>${location.features.map(feature => `<span class="tag">${feature}</span>`).join('')}</div><div class="parking-footer"><span class="price">${money(location.price)} <small>/ hour</small></span><button class="btn btn-primary" data-location="${location.id}">View slots →</button></div></div></article>`).join('') || '<div class="card">No locations match your search.</div>'; }
function slots() { const location = state.selectedLocation || storage.get('pm_locations', seed.locations)[0]; const saved = storage.get('pm_slots', {}); const selected = state.selectedSlot; return layout(`<section class="page"><div class="page-heading"><div><h1>Select your spot</h1><p class="subtitle">${escapeHtml(location.name)} · ${escapeHtml(location.address)}</p></div><button class="btn btn-outline" data-route="parking">← Back to parking</button></div><div class="slot-layout"><div class="card"><div class="card-header"><h2>Ground floor · ${location.available} available</h2><span class="status success">Open</span></div><div class="slot-map"><div class="slot-legend"><span class="legend-item"><i class="legend-swatch"></i>Available</span><span class="legend-item"><i class="legend-swatch selected"></i>Selected</span><span class="legend-item"><i class="legend-swatch occupied"></i>Occupied</span><span class="legend-item"><i class="legend-swatch reserved"></i>Reserved</span></div>${['A','B','C','D','E'].map(row => `<div class="slot-row">${[1,2,3,4,5].map(number => { const id = `${row}${number}`; const seeded = saved[`${location.id}-${id}`] || (id === 'A2' || id === 'C4' ? 'occupied' : id === 'D1' ? 'reserved' : ''); return `<button class="slot ${seeded} ${selected === id ? 'selected' : ''}" data-slot="${id}" ${seeded ? 'disabled' : ''}>${id}</button>`; }).join('')}</div>`).join('')}</div></div><aside class="card"><div class="card-header"><h2>Your selection</h2></div>${selected ? `<div class="summary-list"><div class="summary-line"><span>Parking location</span><strong>${escapeHtml(location.name)}</strong></div><div class="summary-line"><span>Selected slot</span><strong>${selected}</strong></div><div class="summary-line"><span>Floor</span><strong>Ground floor</strong></div><div class="summary-line"><span>Rate</span><strong>${money(location.price)} / hr</strong></div><div class="summary-line total-line"><span>Estimated total</span><strong>${money(location.price * 3)}</strong></div><button class="btn btn-primary btn-block" data-route="booking">Continue booking →</button></div>` : '<div class="centered"><p class="subtitle">Choose an available slot to see your summary.</p></div>'}</aside></div></section>`, 'slots'); }
function bookingPage() { const location = state.selectedLocation || seed.locations[0]; const slot = state.selectedSlot || 'B12'; return layout(`<section class="page"><div class="page-heading"><div><h1>Booking details</h1><p class="subtitle">A few details and your space is reserved.</p></div></div><div class="form-layout"><div class="card"><div class="card-header"><h2>Vehicle and timing</h2><span class="status success">Step 2 of 3</span></div><form id="booking-form" class="form-grid"><div class="field"><label>Full name *</label><input name="name" required value="${escapeHtml(currentUser()?.name || 'Alex Morgan')}"></div><div class="field"><label>Mobile number *</label><input name="phone" required pattern="[0-9+ -]{8,}" placeholder="+1 555 012 3456"></div><div class="field"><label>Vehicle number *</label><input name="vehicle" required placeholder="TN 09 AB 1234"></div><div class="field"><label>Vehicle type</label><select name="vehicleType"><option>Car</option><option>Motorcycle</option><option>EV</option></select></div><div class="field"><label>Parking location</label><input value="${escapeHtml(location.name)}" disabled></div><div class="field"><label>Slot number</label><input value="${slot}" disabled></div><div class="field"><label>Entry date *</label><input name="date" type="date" required value="2026-09-07"></div><div class="field"><label>Entry time *</label><input name="entry" type="time" required value="09:30"></div><div class="field"><label>Exit time *</label><input name="exit" type="time" required value="12:30"></div><div class="full" style="display:flex;justify-content:end;margin-top:5px"><button class="btn btn-primary" type="submit">Continue to payment →</button></div></form></div><aside class="card"><div class="card-header"><h2>Booking summary</h2></div><div class="summary-list"><div class="summary-line"><span>Location</span><strong>${escapeHtml(location.name)}</strong></div><div class="summary-line"><span>Slot</span><strong>${slot}</strong></div><div class="summary-line"><span>Rate</span><strong>${money(location.price)} / hr</strong></div><div class="summary-line total-line"><span>Estimated total</span><strong id="live-total">$13.50</strong></div></div><p class="subtitle" style="margin-top:22px">You can review everything before payment. This demo does not process real payments.</p></aside></div></section>`, 'booking'); }
function payment() { const location = state.selectedLocation || seed.locations[0]; const booking = state.booking; const amount = booking.amount || location.price * 3; return layout(`<section class="page"><div class="page-heading"><div><h1>Complete payment</h1><p class="subtitle">Secure your spot with a demo payment.</p></div></div><div class="form-layout"><div class="card"><div class="card-header"><h2>Payment method</h2><span class="status success">Step 3 of 3</span></div><div class="payment-methods"><button class="method active" data-method="card">▣ Card</button><button class="method" data-method="upi">⌁ UPI</button><button class="method" data-method="cash">$ Cash</button></div><form id="payment-form"><div id="card-fields" class="form-grid"><div class="field full"><label>Card number *</label><input id="card-number" required placeholder="1234 5678 9012 3456" maxlength="19"></div><div class="field"><label>Card holder *</label><input required placeholder="Alex Morgan"></div><div class="field"><label>Expiry *</label><input required placeholder="MM / YY" maxlength="7"></div><div class="field"><label>CVV *</label><input required placeholder="123" maxlength="3"></div></div><div id="upi-fields" class="field" style="display:none"><label>UPI ID *</label><input placeholder="name@bank"></div><button class="btn btn-primary btn-block" style="margin-top:20px" type="submit">Pay ${money(amount)} →</button></form></div><aside class="card"><div class="card-header"><h2>Order summary</h2></div><div class="summary-list"><div class="summary-line"><span>Parking</span><strong>${escapeHtml(location.name)}</strong></div><div class="summary-line"><span>Slot</span><strong>${booking.slot || state.selectedSlot || 'B12'}</strong></div><div class="summary-line"><span>Date</span><strong>${booking.date || '2026-09-07'}</strong></div><div class="summary-line"><span>Duration</span><strong>3 hours</strong></div><div class="summary-line"><span>Base amount</span><strong>${money(amount - 1.2)}</strong></div><div class="summary-line"><span>Service fee</span><strong>$1.20</strong></div><div class="summary-line total-line"><span>Total</span><strong>${money(amount)}</strong></div></div></aside></div></section>`, 'payment'); }
function confirmation() { const booking = storage.get('pm_last_booking', null) || storage.get('pm_bookings', seed.bookings)[0]; return layout(`<section class="page"><div class="confirmation card"><div class="success-icon">✓</div><h1>Booking confirmed</h1><p class="subtitle">Your parking spot is waiting for you. A confirmation has been saved to your account.</p><div class="qr-large"></div><div class="receipt-grid"><div><span>Booking ID</span><strong>${booking.id}</strong></div><div><span>Status</span><strong class="status success">Confirmed</strong></div><div><span>Parking location</span><strong>${escapeHtml(booking.parking)}</strong></div><div><span>Slot</span><strong>${booking.slot}</strong></div><div><span>Vehicle</span><strong>${booking.vehicle}</strong></div><div><span>Date & time</span><strong>${booking.date} · ${booking.entry}</strong></div><div><span>Exit time</span><strong>${booking.exit}</strong></div><div><span>Total amount</span><strong>${money(booking.amount)}</strong></div></div><div class="no-print" style="display:flex;justify-content:center;gap:10px;flex-wrap:wrap"><button class="btn btn-outline" onclick="window.print()">Download receipt</button><button class="btn btn-dark" data-route="bookings">View my bookings</button><button class="btn btn-primary" data-route="dashboard">Back to dashboard</button></div></div></section>`, 'confirmation'); }
function bookings() { const all = storage.get('pm_bookings', seed.bookings); return layout(`<section class="page"><div class="page-heading"><div><h1>My bookings</h1><p class="subtitle">Your parking history, all in one place.</p></div><button class="btn btn-primary" data-route="parking">+ New booking</button></div><div class="card"><div class="card-header"><h2>Booking history</h2><select id="booking-filter" style="border:1px solid var(--line);padding:8px;border-radius:7px"><option>All bookings</option><option>Upcoming</option><option>Completed</option></select></div><div id="booking-history">${bookingTable(all)}</div></div></section>`, 'bookings'); }
function admin() { const bookings = storage.get('pm_bookings', seed.bookings); return layout(`<section class="page"><div class="page-heading"><div><h1>Operations overview</h1><p class="subtitle">A clear view of your parking network today.</p></div><button class="btn btn-primary" data-route="admin-locations">Manage locations →</button></div><div class="stats-grid admin-stats">${stat('Total revenue', '$24,890', '$', '')}${stat('Total bookings', '1,248', '▤', 'blue')}${stat('Occupied slots', '72%', '◈', 'peach')}${stat('Available slots', '148', '⌖', 'purple')}${stat('Registered users', '3,842', '●', '')}</div><div class="grid-2"><div class="card"><div class="card-header"><h2>Revenue overview</h2><span class="subtitle">Last 7 days</span></div><div class="chart">${[45, 61, 52, 78, 65, 88, 74].map((height, index) => `<div class="bar" style="height:${height}%"><span>${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][index]}</span></div>`).join('')}</div></div><div class="card centered"><div class="card-header"><h2>Parking occupancy</h2><span class="subtitle">Live</span></div><div class="donut"></div><strong style="font:700 24px 'Space Grotesk'">72%</strong><p class="subtitle">Average occupancy</p></div></div><div class="card" style="margin-top:20px"><div class="card-header"><h2>Recent transactions</h2><button class="link" data-route="admin-bookings">View all</button></div>${bookingTable(bookings)}</div></section>`, 'admin'); }
function adminLocations() { const locations = storage.get('pm_locations', seed.locations); return layout(`<section class="page"><div class="page-heading"><div><h1>Parking locations</h1><p class="subtitle">Manage the places that keep your city moving.</p></div><button class="btn btn-primary" id="add-location">+ Add parking</button></div><div class="card"><div class="table-wrap"><table class="admin-table"><thead><tr><th>Parking name</th><th>Location</th><th>Total slots</th><th>Available</th><th>Occupied</th><th>Price</th><th>Status</th><th>Actions</th></tr></thead><tbody>${locations.map(l => `<tr><td><strong>${escapeHtml(l.name)}</strong></td><td>${escapeHtml(l.address)}</td><td>${l.total}</td><td>${l.available}</td><td>${l.total - l.available}</td><td>${money(l.price)}</td><td><span class="status success">${l.status}</span></td><td><button class="btn btn-outline" data-edit-location="${l.id}">Edit</button></td></tr>`).join('')}</tbody></table></div></div></section>`, 'admin-locations'); }
function adminSlots() { const location = storage.get('pm_locations', seed.locations)[0]; const saved = storage.get('pm_slots', {}); return layout(`<section class="page"><div class="page-heading"><div><h1>Parking slots</h1><p class="subtitle">Update availability in real time for ${escapeHtml(location.name)}.</p></div><select id="admin-location-select"><option>${escapeHtml(location.name)}</option></select></div><div class="card"><div class="slot-map">${['A','B','C','D','E'].map(row => `<div class="slot-row">${[1,2,3,4,5].map(number => { const id = `${row}${number}`; const status = saved[`${location.id}-${id}`] || ''; return `<button class="slot ${status}" data-admin-slot="${id}">${id}</button>`; }).join('')}</div>`).join('')}</div><p class="subtitle" style="margin-top:16px">Click a slot to cycle through Available, Occupied, Reserved and Maintenance.</p></div></section>`, 'admin-slots'); }
function adminBookings() { return layout(`<section class="page"><div class="page-heading"><div><h1>All bookings</h1><p class="subtitle">Monitor every reservation across your network.</p></div></div><div class="card"><div class="search-panel" style="padding:0;margin-bottom:20px"><div class="field"><label>Search bookings</label><input id="admin-booking-search" placeholder="ID, customer or vehicle"></div><div class="field"><label>Status</label><select><option>All statuses</option><option>Upcoming</option><option>Completed</option></select></div></div><div id="admin-bookings-table">${bookingTable(storage.get('pm_bookings', seed.bookings))}</div></div></section>`, 'admin-bookings'); }
function reports() { return layout(`<section class="page"><div class="page-heading"><div><h1>Reports & analytics</h1><p class="subtitle">Understand demand, revenue and the rhythm of your lots.</p></div><button class="btn btn-outline">Export report ↓</button></div><div class="stats-grid">${stat('Daily bookings', '184', '▤', '')}${stat('Monthly revenue', '$86,420', '$', 'blue')}${stat('Occupancy rate', '72%', '◈', 'peach')}${stat('Peak hour', '6:00 PM', '◷', 'purple')}</div><div class="grid-2"><div class="card"><div class="card-header"><h2>Bookings by day</h2></div><div class="chart">${[55, 42, 68, 83, 64, 92, 76].map((height, index) => `<div class="bar" style="height:${height}%"><span>${['M','T','W','T','F','S','S'][index]}</span></div>`).join('')}</div></div><div class="card"><div class="card-header"><h2>Most used locations</h2></div><div class="activity"><div><strong>Downtown Parking Hub</strong><div class="bar" style="height:10px;width:86%;margin-top:7px"></div></div><div><strong>City Center Smart Parking</strong><div class="bar" style="height:10px;width:70%;margin-top:7px;background:#9ccde9"></div></div><div><strong>Metro Station Parking</strong><div class="bar" style="height:10px;width:55%;margin-top:7px;background:#ffd99f"></div></div></div></div></div></section>`, 'reports'); }
function settings() { return layout(`<section class="page"><div class="page-heading"><div><h1>Settings</h1><p class="subtitle">Make Parkly work the way you do.</p></div></div><div class="grid-2"><div class="card"><div class="card-header"><h2>Profile settings</h2></div><div class="form-grid"><div class="field"><label>Full name</label><input value="${escapeHtml(currentUser()?.name || 'Alex Morgan')}"></div><div class="field full"><label>Email address</label><input value="${escapeHtml(currentUser()?.email || 'demo@parking.com')}"></div><div class="field full"><label>Phone number</label><input placeholder="+1 555 012 3456"></div></div><button class="btn btn-primary" style="margin-top:18px" id="save-settings">Save changes</button></div><div class="card"><div class="card-header"><h2>Preferences</h2></div><div class="activity"><label class="check-row"><span>Booking reminders</span><input type="checkbox" checked></label><label class="check-row"><span>Weekly activity summary</span><input type="checkbox" checked></label><label class="check-row"><span>Dark mode</span><input type="checkbox" id="dark-mode"></label></div></div></div></section>`, 'settings'); }
function login() { app.innerHTML = `<div class="login-page"><section class="login-showcase"><div class="brand"><span class="brand-mark"></span> parkly</div><h1>More time.<br><em style="color:var(--mint);font-style:normal">Less circling.</em></h1><p>One calm, connected workspace for finding, managing and improving every parking experience.</p><div class="feature-list"><div class="feature"><i>✓</i> Reserve in under a minute</div><div class="feature"><i>✓</i> Real-time availability</div><div class="feature"><i>✓</i> Receipts that stay organized</div></div></section><section class="login-panel"><div class="login-box"><div class="login-brand">Welcome back</div><h2>Sign in to Parkly</h2><p class="subtitle">Your parking workspace is ready when you are.</p><div class="demo-box"><strong>Demo access</strong><br>User: demo@parking.com / 123456<br>Admin: admin@parking.com / admin123</div><form class="login-form" id="login-form"><div class="field"><label>Email address</label><input name="email" type="email" required placeholder="you@example.com"></div><div class="field"><label>Password</label><input name="password" type="password" required placeholder="••••••••"></div><div class="check-row"><label><input type="checkbox"> Remember me</label><a class="link" href="#" id="forgot">Forgot password?</a></div><button class="btn btn-primary btn-block" type="submit">Sign in →</button></form><p class="muted-note">New to Parkly? <a class="link" href="#" id="create-account">Create an account</a></p></div></section></div>`; }
function showModal(location = {}) { const isEdit = Boolean(location.id); app.insertAdjacentHTML('beforeend', `<div class="modal-backdrop" id="modal"><div class="modal"><div class="card-header"><h2>${isEdit ? 'Edit parking' : 'Add parking'}</h2><button class="icon-button" id="close-modal">×</button></div><form id="location-form"><div class="form-grid"><div class="field full"><label>Parking name</label><input name="name" required value="${escapeHtml(location.name || '')}"></div><div class="field full"><label>Address</label><input name="address" required value="${escapeHtml(location.address || '')}"></div><div class="field"><label>Total slots</label><input name="total" type="number" required value="${location.total || 50}"></div><div class="field"><label>Price / hour</label><input name="price" type="number" step=".25" required value="${location.price || 4}"></div></div><div class="modal-actions"><button type="button" class="btn btn-outline" id="cancel-modal">Cancel</button><button class="btn btn-primary">Save location</button></div></form></div></div>`); }
function bind() {
  document.querySelectorAll('[data-route]').forEach(button => button.addEventListener('click', () => { location.hash = `#/${button.dataset.route}`; }));
  document.querySelector('#mobile-menu')?.addEventListener('click', () => document.querySelector('#sidebar').classList.toggle('open'));
  document.querySelector('#logout')?.addEventListener('click', () => { localStorage.removeItem('pm_user'); location.hash = '#/login'; render(); });
  document.querySelector('#notify')?.addEventListener('click', () => toast('You are all caught up.'));
  document.querySelectorAll('[data-location]').forEach(button => button.addEventListener('click', () => { state.selectedLocation = storage.get('pm_locations', seed.locations).find(l => l.id === Number(button.dataset.location)); state.selectedSlot = null; location.hash = '#/slots'; }));
  document.querySelectorAll('[data-slot]').forEach(button => button.addEventListener('click', () => { state.selectedSlot = button.dataset.slot; render(); }));
  document.querySelector('#search-parking')?.addEventListener('click', () => { const query = document.querySelector('#location-search').value.toLowerCase(); const result = storage.get('pm_locations', seed.locations).filter(l => `${l.name} ${l.address}`.toLowerCase().includes(query)); document.querySelector('#parking-results').innerHTML = locationCards(result); bind(); });
  document.querySelector('#booking-form')?.addEventListener('submit', event => { event.preventDefault(); if (!event.target.checkValidity()) return event.target.reportValidity(); const data = Object.fromEntries(new FormData(event.target)); const location = state.selectedLocation || seed.locations[0]; const entry = new Date(`2026-01-01T${data.entry}`); const exit = new Date(`2026-01-01T${data.exit}`); const hours = Math.max(1, Math.ceil((exit - entry) / 3600000)); state.booking = { ...data, parking: location.name, slot: state.selectedSlot || 'B12', amount: location.price * hours + 1.2, hours }; location.hash = '#/payment'; });
  document.querySelectorAll('[data-method]').forEach(button => button.addEventListener('click', () => { state.paymentMethod = button.dataset.method; document.querySelectorAll('[data-method]').forEach(item => item.classList.toggle('active', item === button)); document.querySelector('#card-fields').style.display = state.paymentMethod === 'card' ? 'grid' : 'none'; document.querySelector('#upi-fields').style.display = state.paymentMethod === 'upi' ? 'block' : 'none'; }));
  document.querySelector('#card-number')?.addEventListener('input', event => { event.target.value = event.target.value.replace(/\D/g, '').replace(/(.{4})/g, '$1 ').trim(); });
  document.querySelector('#payment-form')?.addEventListener('submit', event => { event.preventDefault(); if (!event.target.checkValidity()) return event.target.reportValidity(); const booking = { id: `PK-${Math.floor(100000 + Math.random() * 899999)}`, parking: state.booking.parking || 'Downtown Parking Hub', slot: state.booking.slot || 'B12', vehicle: state.booking.vehicle || 'TN 09 AB 1234', date: state.booking.date || '2026-09-07', entry: state.booking.entry || '09:30', exit: state.booking.exit || '12:30', amount: state.booking.amount || 15.2, status: 'Upcoming' }; const bookings = storage.get('pm_bookings', seed.bookings); storage.set('pm_bookings', [booking, ...bookings]); storage.set('pm_last_booking', booking); const submit = event.target.querySelector('button[type=submit]'); submit.disabled = true; submit.textContent = 'Confirming payment...'; setTimeout(() => { location.hash = '#/confirmation'; }, 700); });
  document.querySelector('#booking-filter')?.addEventListener('change', event => { const value = event.target.value; document.querySelector('#booking-history').innerHTML = bookingTable(storage.get('pm_bookings', seed.bookings).filter(b => value === 'All bookings' || b.status === value)); });
  document.querySelector('#admin-booking-search')?.addEventListener('input', event => { const query = event.target.value.toLowerCase(); const filtered = storage.get('pm_bookings', seed.bookings).filter(b => Object.values(b).join(' ').toLowerCase().includes(query)); document.querySelector('#admin-bookings-table').innerHTML = bookingTable(filtered); });
  document.querySelector('#add-location')?.addEventListener('click', () => showModal()); document.querySelectorAll('[data-edit-location]').forEach(button => button.addEventListener('click', () => showModal(storage.get('pm_locations', seed.locations).find(l => l.id === Number(button.dataset.editLocation)))));
  document.querySelector('#close-modal')?.addEventListener('click', () => document.querySelector('#modal').remove()); document.querySelector('#cancel-modal')?.addEventListener('click', () => document.querySelector('#modal').remove());
  document.querySelector('#location-form')?.addEventListener('submit', event => { event.preventDefault(); const form = Object.fromEntries(new FormData(event.target)); const locations = storage.get('pm_locations', seed.locations); locations.push({ id: Date.now(), ...form, total: Number(form.total), available: Number(form.total), price: Number(form.price), distance: '0.8 mi', rating: 4.7, status: 'Open', features: ['Security'], tone: '' }); storage.set('pm_locations', locations); document.querySelector('#modal').remove(); toast('Parking location added'); render(); });
  document.querySelectorAll('[data-admin-slot]').forEach(button => button.addEventListener('click', () => { const location = storage.get('pm_locations', seed.locations)[0]; const slots = storage.get('pm_slots', {}); const key = `${location.id}-${button.dataset.adminSlot}`; const states = ['', 'occupied', 'reserved', 'maintenance']; slots[key] = states[(states.indexOf(slots[key] || '') + 1) % states.length]; storage.set('pm_slots', slots); render(); toast(`Slot ${button.dataset.adminSlot} updated`); }));
  document.querySelector('#save-settings')?.addEventListener('click', () => toast('Settings saved successfully'));
  document.querySelector('#dark-mode')?.addEventListener('change', event => { document.body.classList.toggle('dark', event.target.checked); storage.set('pm_dark', event.target.checked); });
}
function render() { if (!currentUser() && route() !== 'login') { location.hash = '#/login'; return; } const views = { dashboard, parking, slots, booking: bookingPage, payment, confirmation, bookings, admin, 'admin-locations': adminLocations, 'admin-slots': adminSlots, 'admin-bookings': adminBookings, reports, settings }; if (route() === 'login') return login(); app.innerHTML = views[route()] ? views[route()]() : dashboard(); bind(); if (storage.get('pm_dark', false)) document.body.classList.add('dark'); }
window.addEventListener('hashchange', render); render();
document.addEventListener('submit', event => { if (event.target.id !== 'login-form') return; event.preventDefault(); const data = Object.fromEntries(new FormData(event.target)); const adminUser = data.email.toLowerCase().startsWith('admin'); storage.set('pm_user', { name: displayNameFromEmail(data.email), email: data.email, role: adminUser ? 'admin' : 'user' }); location.hash = adminUser ? '#/admin' : '#/dashboard'; render(); });
document.addEventListener('click', event => { if (event.target.id === 'forgot') { event.preventDefault(); toast('Demo mode: password reset is not connected.'); } if (event.target.id === 'create-account') { event.preventDefault(); toast('Demo mode: use the provided login credentials.'); } });
